feat: added prev_owner to response log
public-awesome/cw-nfts pull request #12
Opened 2021-10-11 03:32 UTC by edison0x

Resolves https://github.com/CosmWasm/cw-nfts/issues/11

Useful feature and have added it in.

2021-10-11 17:51 UTC, JakeHartnell commented on contracts/cw721-base/src/contract_tests.rs
>              .add_attribute("sender", "venus")
Language is a bit confusing her now... we have `sender`, `ricpient`, and `from`...

2021-10-11 17:54 UTC, JakeHartnell commented on contracts/cw721-base/src/contract_tests.rs
>              .add_attribute("sender", "venus")
Almost like @larry0x's comment of using `from` and `to` like the Ethereum transfer events.

It is important to maintain sender, as that may be different than the owner, even though there is a little duplication there.

2021-10-11 17:57 UTC, JakeHartnell commented on contracts/cw721-base/src/contract_tests.rs
>              .add_attribute("sender", "venus")
Also, whatever we decide should be consistent with `SendNft`.

2021-10-11 17:58 UTC, JakeHartnell requested changes
`TransferNFT` needs to be consistent with `SendNFT`.

2021-10-11 20:31 UTC, JakeHartnell commented
What do folks think about using `to` over `recipient`? Mirroring Ethereum: https://ethereum.org/en/developers/docs/standards/tokens/erc-721/#events

2021-10-11 21:53 UTC, the-frey commented
FWIW I'm in favour of sticking close to the ETH standards where possible. `from` and `to` are probably the way to go in that case IIUC.

2021-10-11 22:42 UTC, alwin-peng commented
I think we should continue with `recipient`. CW20 is already widely used at this point and uses `recipient`.

2021-10-11 22:49 UTC, the-frey commented
Hmmm, I suppose I'm looking at the POV of devs who are coming from ETH/ERC721 land. Although can see the argument for CW20 style too 🤷

2021-10-12 07:57 UTC, edisonljh commented
I think that we might be better to stick with the current CW standards.
Though i see the point of standardising with the Ethereum contracts, but there should be consistency amongst the CosmWasm contracts.

Changing everything to Ethereum sounds like a lot of work in code-change and communication with exisiting protocols. So perhaps let's avoid that.

2021-10-12 09:30 UTC, orkunkl approved these changes
LGTM

2021-10-14 15:51 UTC, ALPAC-4 commented
And I think we need to add owner at mint response log

https://github.com/CosmWasm/cw-nfts/blob/2712c05fbc365a44809c904f8508410c4f70383e/contracts/cw721-base/src/execute.rs#L111

I think owner is more important information than minter. Minter is always same for same contract

2022-04-21 03:19 UTC, shanev commented
This issue is a bit stale. Okay to close?

2022-07-17 02:28 UTC, JakeHartnell commented
> This issue is a bit stale. Okay to close?

Yeah.

2022-07-17 02:28 UTC, closed without merging

2023-09-05 15:20 UTC, peara commented
@JakeHartnell @larry0x  @shanev Please reconsider this PR. This is very useful for indexers and apps and for the consistency of cw721 as well.
I think adding `owner` as already implemented is good enough. The only issue remaining is adding the same to `send_nft` and `mint`, is that right?