feat: add cw721 editions contract
public-awesome/cw-nfts pull request #36
Opened 2021-12-19 17:50 UTC by verminator23

2021-12-19 21:16 UTC, JakeHartnell submitted a review, later dismissed
Very nice! Great to have an example like this. Only thing I'm not 100% sold on is the name for this contract... because it's not actually a `cw721` but rather a contract that uses one.

Curious what others think, but otherwise LGTM.

2021-12-20 06:45 UTC, verminator23 commented
@JakeHartnell Good point. I can rename it to just "editions".

2021-12-20 08:26 UTC, orkunkl commented
I think using `cw721-x` naming is convenient for extensions, or maybe `cw721-ext-x` @ethanfrey @JakeHartnell wdyt ?
@verminator23 renaming the project to `cw721-fixed-price` makes sense.

2021-12-20 08:27 UTC, orkunkl requested changes
We should resolve project naming.

2021-12-20 12:14 UTC, ethanfrey commented
This looks like a very useful functionality (cw721 minting contract) that many people have asked for. They can either use this as is, or as inspiration to customize further. It think this is a valuable addition.

About the naming, we use `cw20-` for a number of related contracts, not just `cw20-staking`, which implements `cw20` interface, but also `cw20-escrow` and `cw20-ics20` which accept cw20 tokens and do something with them. As long as it is clear in the README, I think this is fine.

I haven't done a code review (just a brief skim), but I support adding it here (after someone does a better review)

2021-12-20 12:15 UTC, ethanfrey commented
`cw721-editions`
`cw721-minter`
`cw721-fixed-price`
`cw721-so-this-is-how-you-let-people-mint-nfts-by-paying`

are all fine with me. Naming is tough. But let's not kick ourselves too much and just pick something that is "good enough"

2021-12-20 15:49 UTC, verminator23 commented
Appreciate the comments from everyone. Will rename it to "cw721-fixed-price" later today.

2021-12-21 03:57 UTC, verminator23 commented
Changed the name of the contract to cw721-fixed-price. Lmk if there's anything else you guys think could be improved.

2021-12-21 10:28 UTC, the-frey commented
Code looks good, but some way of expressing it's paid for in CW20 in the naming (hard I know 🙃) would be my only nitpick

`cw721-mint-with-cw20`?
`cw721-mint-paid-with-cw20`?

Ew. Actually:

`cw20-mints-cw721` is probably the shortest I can think of

2021-12-24 11:44 UTC, orkunkl approved these changes, later dismissed

2021-12-24 11:45 UTC, orkunkl commented on contracts/cw721-fixed-price/Cargo.toml
> +cw721-base = { path = "../cw721-base", version = "0.10.1" }
```suggestion
cw721-base = { path = "../cw721-base", version = "0.10.1" features = [ "library"] }
```

2021-12-24 11:45 UTC, orkunkl commented on contracts/cw721-fixed-price/Cargo.toml
> +cw721-base = { path = "../cw721-base", version = "0.10.1" }
This will reduce the code size

2021-12-26 21:23 UTC, JakeHartnell approved these changes, later dismissed
LGTM, nice to have an example like this.

2021-12-29 09:37 UTC, orkunkl submitted a review, later dismissed
LGTM

2022-01-05 01:41 UTC, JakeHartnell submitted a review, later dismissed
LGTM

2022-01-05 05:53 UTC, orkunkl commented on contracts/cw721-fixed-price/examples/schema.rs
> +    export_schema(&schema_for!(QueryMsg), &out_dir);
Best to add `Config` here too

2022-01-05 06:36 UTC, orkunkl submitted a review, later dismissed

2022-01-09 20:20 UTC, orkunkl approved these changes
🚀

2022-01-09 20:20 UTC, merged